

title: < ProCode />
email: your-email@example.com
name: ProProfit
author: Proname
description:
# this means to ignore newlines until "baseurl:"
  lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem 
  lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem 
baseurl: "" # the subpath of your site, e.g. /blog
url: "ercua.github.io/ProCode.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
markdown: kramdown
# Build settings
remote_theme: ProCode
plugins:
  - jekyll-feed
  - jekyll-sass-converter

date_format: "%d.%m.%Y"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# SASS
sass:
  style: compressed
  sourcemap: never
  sass_dir: _sass
